# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pylady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('github', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
