# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20160816_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pylady',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
